version: "3.7"
services:

  pokedex_php:
    container_name: pokedex_php
    build: ./php/
    volumes:
      - ./../pokedex:/var/www/html
    ports:
      - 8150:80
    depends_on:
      - pokedex_mysql

  pokedex_mysql:
    container_name: pokedex_mysql
    restart: always
    image: mysql:5.7.24
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  pokedex_phpmyadmin:
    container_name: pokedex_phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 8050:80
    environment:
      PMA_HOST: pokedex_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456
